defaults:
  - dclaw_fptd.yaml
  - _self_


alg:
  env_name: DclawSysID
  batch_size: 1
  num_envs: 1

task:
  env:
    loadCADPTD: True
    name: DclawSysID

logging:
  wandb:
    project: dexenv
  log_interval: 1

cam:
  height: 480
  width: 640
  hov: 65