defaults:
  - dclaw_fptd.yaml
  - _self_


alg:
  env_name: DclawRealPTD
  batch_size: 20
  num_envs: 60
  # pretrain_model: /workspace/dexenv/dexenv/pretrained/artifacts/student/train-model.pt

task:
  env:
    loadCADPTD: True
    name: DclawRealPTD

logging:
  wandb:
    project: dexenv
  log_interval: 1