defaults:
  - dclaw_sysid.yaml
  - _self_

task:
  headless: False
  obj:
    num_objs: 1
  env:
    stiffness: [2.772, 3.558, 3.558, 2.772, 3.558, 3.558, 2.772, 3.558, 3.558, 2.772, 3.558, 3.558]
    damping: [0.273, 0.382, 0.382, 0.273, 0.382, 0.382, 0.273, 0.382, 0.382, 0.273, 0.382, 0.382]

alg:
  num_envs: 625
  batch_size: 1
  train_rollout_steps: 60
  eval_rollout_steps: 120
  opt_epochs: 2

logging:
  wandb:
    mode: offline
